# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: "build binary"
    cmds:
      - go build -o ./nav ./main.go 
      - echo 'run `eval "$(./nav)"` in your terminal to complete setup'
    silent: true
  install:
    desc: "installs binary from source using golang"
    cmds:
      - GOPROXY=direct go install github.com/nanvenomous/nav@latest
  tape:
    desc: "run integration tapes"
    cmds:
      - VHS_NO_SANDBOX=true vhs tapes/dn.tape
      - VHS_NO_SANDBOX=true vhs tapes/t.tape
      - VHS_NO_SANDBOX=true vhs tapes/to.tape
      # - VHS_NO_SANDBOX=true vhs tapes/up.tape
      - firefox tapes
