# Navigation functions generated by nav CLI
# Add this to your .bashrc, .zshrc, or shell config

_nav_get_list_command() {
    if command -v eza >/dev/null 2>&1; then
        eza --tree --level=1 --group-directories-first
    elif command -v tree >/dev/null 2>&1; then
        tree -C -L 1 --dirsfirst
    else
        case "$(uname -s)" in
            Linux*)   ls --color=auto --group-directories-first -1 2>/dev/null || ls -1 ;;
            Darwin*)  ls -G -1 ;;
            *)        ls -1 ;;
        esac
    fi
}

_nav_get_files_command() {
    if command -v eza >/dev/null 2>&1; then
        eza --level -1 --group-directories-first | grep -v '/$'
    elif command -v tree >/dev/null 2>&1; then
        tree -C -L 1 -F | grep -v /$
    else
        case "$(uname -s)" in
            Linux*)   ls --color=auto -1 -p 2>/dev/null | grep -v '/$' ;;
            Darwin*)  ls -G -1 -p | grep -v '/$' ;;
            *)        ls -1 -p | grep -v '/$' ;;
        esac
    fi
}

up() {
    local levels=${1:-1}
    
    if ! [[ "$levels" =~ ^[0-9]+$ ]] || [ "$levels" -lt 1 ]; then
        echo "Error: levels must be a positive integer" >&2
        return 1
    fi
    
    for ((i=1; i<=levels; i++)); do
        cd .. || return 1
    done
    
    clear
    _nav_get_list_command
}

t() {
    clear
    _nav_get_list_command
}

dn() {

    if [ ! -n "$1" ]; then
        cd
        clear
        _nav_get_list_command
        return 0
    fi

    if [ ! -d "$1" ]; then
        echo "Error: '$1' is not a directory" >&2
        return 1
    fi
    
    cd "$1" || return 1
    clear
    _nav_get_list_command
}

to() {
    if ! command -v fzf >/dev/null 2>&1; then
        echo "Error: fzf is required. Please install fzf first." >&2
        return 1
    fi
    
    while true; do
        clear

        local current_dir=$(pwd)
        local options=""
        
        # Show files first (non-directories)
        
        # Add .. option if not at root
        if [ "$current_dir" != "/" ]; then
            options=".."
        fi
        
        # Add subdirectories
        local dirs=""
        if ls -d */ >/dev/null 2>&1; then
            dirs=$(ls -1 -d */ 2>/dev/null | sed 's|/||' | grep -v '^\.' | sort)
        fi
        
        if [ -n "$dirs" ]; then
            if [ -n "$options" ]; then
                options="$options"$'\n'"$dirs"
            else
                options="$dirs"
            fi
        fi
        
        if [ -z "$options" ]; then
            break
        fi
        
        local selection=$(echo "$options" | fzf \
            --prompt "$current_dir" \
            --height 40% \
            --layout reverse \
            --border \
            --exit-0)
        
        local exit_code=$?
        if [ $exit_code -ne 0 ]; then
            break
        fi
        
        if [ -z "$selection" ]; then
            break
        fi
        
        if [ "$selection" = ".." ]; then
            cd .. || break
        else
            cd "$selection" || break
        fi
    done
}

# Set up bash completion
if [ -n "$BASH_VERSION" ]; then
    complete -o nospace -o dirnames dn
fi

# Set up zsh completion  
if [ -n "$ZSH_VERSION" ]; then
    compdef '_path_files -/' dn
fi
