name: Integration
on: [push, pull_request]
jobs:
  integration-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.4'

      - name: Install dependencies & build
        run: make

      - name: set path
        run: echo "$(pwd)" >> $GITHUB_PATH

      - name: integration tests
        run: |
          go test -v ./...
